apiVersion: v1
kind: ConfigMap
metadata:
  name: transaction-service-config
data:
  application.yml: |
    spring:
      application:
        name: transaction-service
    
    server:
      port: 8080
    
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics 